### ISSUE TITLE
Create Model for AccountGroupMasterPayments

### ISSUE THREAD

**Issue by rajaduraikrishna** [rmhari/rentmanager-java-sdk#3]

**Comment by sguruvammal2020** [comment]
Sir, I could not find this entity from rentmanager API. This is not available there.

**Comment by sguruvammal2020** [comment]
Sir,
I have checked under API Resources tab in renmanager API.
I got this as reply:
AccountGroupMasterPayments Retrieve Collection
(DEPRECATED) As of 3/4/2019 replaced by AccountGroupPayments
